ruby '2.0.0'

# Site settings
title: TechTalk
email: ryan@ryanhelms.com

description: "A techie-with-an-attitude working with technologies like ServiceStack.net, ASP.NET, SQL Server, jQuery, Bootstrap and many more."
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://ryanhelmsblog.github.io" # the base hostname & protocol for your site
twitter_username: ryanhelms
github_username:  ryanhelms

highlighter: pygments
#highlighter: rouge

markdown: kramdown
